apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.elastic.co'
    targetRevision: 7.11.2
    chart: kibana
  destination:
    namespace: elastic
    name: lk-test.k8s.local
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
